services:
  - type: web
    name: pay-to-post
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    envVars:
      IPN_SECRET: "${IPN_SECRET}"

  - type: worker
    name: pay-to-post-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      BOT_TOKEN: "${BOT_TOKEN}"
      NOWPAYMENTS_API_KEY: "${NOWPAYMENTS_API_KEY}"
      IPN_SECRET: "${IPN_SECRET}"
