services:
  - type: web
    name: pay-to-post-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    envVars:
      IPN_SECRET:
        fromGroup: pay2post
      NOWPAYMENTS_API_KEY:
        fromGroup: pay2post
      BOT_TOKEN:
        fromGroup: pay2post
