services:
  - type: web
    name: pay-to-post-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    envVars:
      - key: IPN_SECRET
        fromGroup: pay2post

  - type: worker
    name: pay-to-post-bot-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        fromGroup: pay2post
      - key: NOWPAYMENTS_API_KEY
        fromGroup: pay2post
      - key: IPN_SECRET
        fromGroup: pay2post
