services:
  - type: web
    name: pay-to-post-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app & python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
      - key: NOWPAYMENTS_API_KEY
        value: ${NOWPAYMENTS_API_KEY}
      - key: IPN_SECRET
        value: ${IPN_SECRET}
