services:
  - type: web
    name: pay-to-post-webhook
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: NOWPAYMENTS_API_KEY
        sync: false
      - key: IPN_SECRET
        sync: false
